# Generated by Django 4.2.2 on 2023-11-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lobby', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SnakeoWeb.lobby')),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_owner', to='SnakeoWeb.player'),
        ),
    ]
