# Generated by Django 4.2.2 on 2023-11-09 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SnakeoWeb', '0002_alter_lobby_id_user_alter_lobby_owner_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SnakeoWeb.lobby')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lobby',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_owner', to='SnakeoWeb.lobbyuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
